# Generated by parse_spec.py
# Do not modify
import numpy as np

radarsite = [("country", "30c"),
             ("province", "20c"),
             ("station", "40c"),
             ("stationnumber", "10c"),
             ("radartype", "20c"),
             ("Longitude", "16c"),
             ("Latitude", "16c"),
             ("Longitudevalue", "i4"),
             ("Latitudevalue", "i4"),
             ("height", "i4"),
             ("Maxangle", "i2"),
             ("Opangle", "i2"),
             ("MangFreq", "i2")]

radarsite_dtype = np.dtype(radarsite)

performance = [("AntennaG", "i4"),
               ("BeamH", "u2"),
               ("BeamL", "u2"),
               ("polarizations", "B"),
               ("sidelobe", "c"),
               ("Power", "i4"),
               ("wavelength", "i4"),
               ("logA", "u2"),
               ("LineA", "u2"),
               ("AGCP", "u2"),
               ("clutterT", "B"),
               ("VelocityP", "B"),
               ("filderP", "B"),
               ("noiseT", "B"),
               ("SQIT", "B"),
               ("intensityC", "B"),
               ("intensityR", "B")]

performance_dtype = np.dtype(performance)

layer_param = [("ambiguousp", "B"),
               ("Arotate", "u2"),
               ("Prf1", "u2"),
               ("Prf2", "u2"),
               ("spulseW", "u2"),
               ("MaxV", "u2"),
               ("MaxL", "u2"),
               ("binWidth", "u2"),
               ("binnumber", "u2"),
               ("recordnumber", "u2"),
               ("Swangles", "i2")]

layer_param_dtype = np.dtype(layer_param)

observation_param = [("stype", "B"),
                     ("syear", "u2"),
                     ("smonth", "B"),
                     ("sday", "B"),
                     ("shour", "B"),
                     ("sminute", "B"),
                     ("ssecond", "B"),
                     ("Timep", "B"),
                     ("smillisecond", "u4"),
                     ("calibration", "B"),
                     ("intensityI", "B"),
                     ("VelocityP_1", "B"),
                     ("layerparam", layer_param_dtype, 30),
                     ("RHIA", "u2"),
                     ("RHIL", "i2"),
                     ("RHIH", "i2"),
                     ("Eyear", "u2"),
                     ("Emonth", "B"),
                     ("Eday", "B"),
                     ("Ehour", "B"),
                     ("Eminute", "B"),
                     ("Esecond", "B"),
                     ("Etenth", "B")]

observation_param_dtype = np.dtype(observation_param)

