# Generated by parse_spec.py
# Do not modify
import numpy as np

header = [
    ("filetype", "u2"),
    ("longitude", "i2"),
    ("latitude", "i2"),
    ("v_beam_width", "B"),
    ("h_beam_width", "B"),
    ("height", "u2"),
    ("reserved", "S22"),
]

header_dtype = np.dtype(header)

data_block = [
    ("radial_time", "u4"),
    ("radial_date", "u4"),
    ("unambiguous_dist", "u2"),
    ("azimuth", "u2"),
    ("az_num", "u2"),
    ("elevation", "u2"),
    ("el_num", "u2"),
    ("radial_index", "u2"),
    ("first_gate_dist", "u2"),
    ("gate_length", "u2"),
    ("gate_num", "u2"),
    ("reserved", "S26"),
    ("tref_pt", "u2"),
    ("ref_pt", "u2"),
    ("vel_pt", "u2"),
    ("sw_pt", "u2"),
    ("zdr_pt", "u2"),
    ("phi_pt", "u2"),
    ("kdp_pt", "u2"),
    ("rho_pt", "u2"),
    ("tref", "2000B"),
    ("ref", "2000B"),
    ("vel", "2000B"),
    ("sw", "2000B"),
    ("zdr", "2000B"),
    ("phi", "2000B"),
    ("kdp", "2000B"),
    ("rho", "2000B"),
    ("res2", "S4"),
]

data_block_dtype = np.dtype(data_block)

radial = [("header", header_dtype), ("data", data_block_dtype)]

radial_dtype = np.dtype(radial)
