# Generated by parse_spec.py
# Do not modify
import numpy as np

message_header = [("product_code", ">i2"),
                  ("date", ">i2"),
                  ("time", ">i4"),
                  ("file_length", ">i4"),
                  ("stid", ">i2"),
                  ("dst_id", ">i2"),
                  ("block_num", ">i2")]

message_header_dtype = np.dtype(message_header)

product_dsc = [("divider", ">i2"),
               ("Latitude", ">i4"),
               ("Longitude", ">i4"),
               ("height", ">i2"),
               ("product_code_", ">i2"),
               ("op_mode", ">i2"),
               ("vcp", ">i2"),
               ("seq_num", ">i2"),
               ("vol_scan_num", ">i2"),
               ("vol_start_date", ">i2"),
               ("vol_start_time", ">i4"),
               ("prod_gen_date", ">i2"),
               ("prod_gen_time", ">i4"),
               ("dependence_1", "2>i2"),
               ("el_num", ">i2"),
               ("dependence_2", ">i2"),
               ("threshold", "16>i2"),
               ("dependence_3", "6>i2"),
               ("ver", ">i2"),
               ("gap_sym", ">i4"),
               ("gap_graphic", ">i4"),
               ("gap_alpha", ">i4")]

product_dsc_dtype = np.dtype(product_dsc)

prod_symbology = [("divider_2", ">i2"),
                  ("block_id", ">i2"),
                  ("block_length", ">i4"),
                  ("layer_num", ">i2")]

prod_symbology_dtype = np.dtype(prod_symbology)

layer = [("layer_divider", ">i2"),
         ("layer_length", ">i4")]

layer_dtype = np.dtype(layer)

radial_packect = [("code", ">i2"),
                  ("first_bin", ">i2"),
                  ("bin_count", ">i2"),
                  ("x_center", ">i2"),
                  ("y_center", ">i2"),
                  ("scale", ">i2"),
                  ("radial_count", ">i2")]

radial_packect_dtype = np.dtype(radial_packect)

radial = [("RLEcount", ">i2"),
          ("angle_start", ">i2"),
          ("angle_delta", ">i2"),
          ("run", ">i4"),
          ("color", ">i4")]

radial_dtype = np.dtype(radial)

